### ISSUE TITLE
Auto adjust the highlight font colour based on the terminal background?

### ISSUE THREAD

**Issue by kianmeng** [RyojiSeto/nano-monitor#1]
As you can see, with highlighted white colour doesn't render well with GNOME Terminal's `black on light yellow` colour scheme:

![image](https://github.com/user-attachments/assets/19f946f7-5089-415d-af7a-41f4a555bf64)

![image](https://github.com/user-attachments/assets/85b1de4b-76aa-46a2-8995-078d986f157e)

**Comment by RyojiSeto** [comment]
Hi kianmeng,

Thank you for your suggestion and for pointing out the issue with highlight visibility. I really appreciate your feedback!

I looked into it, and unfortunately, it seems challenging to detect the terminal's background color automatically from the script. However, you can manually adjust the highlight color by modifying the `COLOR_WHITE` value in the script (line 28). If you're using a light background, changing the value to black (`\033[30m`) should improve visibility.

Sorry for the inconvenience, and thank you for bringing this to my attention. Please let me know if there are any other improvements you'd like to suggest!

Best regards,  
Ryoji Seto
